name: Unit tests

on:
  push:
  pull_request:

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: "Create virtualenv"
        run: python3 -m venv venv/
      - name: "Install dependencies"
        run: venv/bin/pip install -r pip-requirements.txt
      - name: "Run unit tests"
        run: venv/bin/python -m unittest discover -s tests/