name: Unit tests

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  unittest:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        py_ver: ["3.7", "3.8", "3.9"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py_ver }}

      - name: "Create virtualenv"
        run: python -m venv venv/

      - name: "Activate virtualenv"
        run: venv/Scripts/Activate.ps1
        if: ${{ matrix.os == 'windows-latest' }}

      - name: "Activate virtualenv"
        run: source venv/bin/activate
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest' }}

      - name: "Upgrade pip"
        run: python -m pip install --upgrade pip

      - name: "Install package"
        run: python -m pip install -e .

      - name: "Run unit tests"
        run: python -m unittest discover -s tests/
